cloudformation/proxy-service.yaml
tests/load/serverless.yml

Add auto scaling for ecs tasks based on average cpu utilization. 
Enable ECS tasks to scale based on average cpu utilization above 51% and scale down on average cpu utilization bellow 40%.

Cloudformation: Adding ECS Auto Scaling

---

adzerk/transform.py
tests/fixtures/mock_decision.py
tests/fixtures/mock_spoc.py
tests/unit/test_adzerk_transform.py

Pass topics from AdZerk to the client. Sponsored content can have one or multiple topics that allow for client-side personalization.
On the AdZerk side this is implemented as a custom property. AdZerk supports passing these in the 'data' or 'body' object. I opted for the 'body' approach to prevent existing fields (title, url, etc.) from getting mingled with 25 topic fields. This way the response is still readable for humans. The downside is that the 'body' object is json-encoded encoded twice.

Added topics to response

---

adzerk/transform.py
tests/fixtures/mock_decision.py
tests/fixtures/mock_spoc.py
tests/unit/test_adzerk_transform.py

Mozilla will run a campaign in the collection component that shouldn't have a "Sponsored by" subtitle. To remove this, we'll leave the sponsor field empty and remove it in the proxy server.

Make sponsor field optional

---

adzerk/api.py
conf/adzerk.py
tests/fixtures/mock_placements.py
tests/unit/test_adzerk_api.py

The only targeting parameter that distinguishes Story Collections from 3x7 is the Zone. Older versions of Firefox do not specify a Zone, but going forward, all requests to AdZerk should have one. This change will set 217995 (which maps to the 3x7 zone) as the default.

Set a default zone

---

adzerk/transform.py
tests/fixtures/mock_spoc.py

The localization of "Sponsored by" is not yet happening in Firefox 75, so we need to return a context field for collections.
- I filed [a bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1618064) to discuss moving the localization to Firefox for 76.

Add context to story collection

---

app/client.py
app/main.py
tests/unit/test_app.py

We've started targeting spocs by geolocation in AdZerk and need to give developers a way to override which region they are in. This PR adds a `country` and a `region` query parameter to override those keywords.

Added country and region parameters

---

adzerk/api.py
tests/unit/test_adzerk_api.py

Change the keyword format for country and region to match ISO 3166-2. This has two advantages:
1. It's standardized, so ad-ops can easily look up the right code in the [ISO Online Browsing Platform](https://www.iso.org/obp/ui/#search/code/).
2. By adding the country code to the region keyword, targeting regions is simplified. `country-US, region-CA` is turned into `US-CA`.

Change geolocation keyword format to match ISO 3166

---

adzerk/transform.py
tests/fixtures/mock_decision.py
tests/fixtures/mock_spoc.py
tests/unit/test_adzerk_transform.py

Allow the 'sponsored by' label to be hidden for spocs coming from Mozilla or Pocket. We've chosen the keyword `blank` or `empty` to return an empty string for `sponsored_by_override`.

Return empty sponsored_by_override if 'blank' in AdZerk

---

conf/spocs.py

Introduce feature flags that allow us to remotely control whether an experimental feature is enabled. This can be used to quickly turn off a feature if it is not working as expected.
We might eventually want to fetch these values from an admin tool, but because this is time-sensitive I did something quick.

Set spoc v2 feature flag

---

conf/spocs.py

Disable the spoc v2 experiment. The experiment branch causes low-priority spocs to be served over higher-priority ones, and was disruptive for the revenue team. We'll find solutions for the problems we ran into and run another experiment.

Disable spoc v2

---

.circleci/config.yml

Fix CircleCI error during prod deployment:
```
invalid argument "/proxy-server-dev:5b01f1f851a6db58c595407bf3a3d43afd333df0" for "-t, --tag" flag: invalid reference format
```

Fix image name being wrong on prod

---

.circleci/config.yml

Fix typo that failed deployment to prod:
```
invalid argument "/proxy:6e3535cfa7de463a0b1e19b0fe2187acc37f2603" for "-t, --tag" flag: invalid reference format
```

Fixed typo in prod deployment

---

adzerk/api.py
adzerk/transform.py
conf/adzerk.py
tests/fixtures/mock_decision.py
tests/fixtures/mock_spoc.py
tests/unit/test_adzerk_api.py
tests/unit/test_adzerk_transform.py
tests/unit/test_app.py

This returns the weight of AdZerk's priorities. Priorities are designated by a number: 1 is the highest priority while 100 is lowest.
- This is a quick solution to refresh priorities. A better solution would be to have a shared cache that is updated using a Lambda, such that we're only making one request to AdZerk per hour. Even better would be if AdZerk's API would allow us to specify which fields we would like to get back, so we wouldn't have to manage this state ourselves.
- If the priority is not set, we return the lowest priority value of 100.

Add new field 'priority'

---

app/adzerk/api.py

There are a number of 5xx errors since moving to fastapi. All the errors https://sentry.prod.mozaws.net/operations/proxyserver/issues/10489778/?query=is%3Aunresolved point to a timeout in the decision API from level. 
The theory is that the switch to aiohttp was not 1:1 with timeout values. However, the Kevel should never take longer than a second to respond.

Increase Kevel Timeout

---

app/adzerk/api.py

Based on https://github.com/aio-libs/aiohttp/issues/4015#issuecomment-526108921 we are increasing the timeout in aiohttp. The theory is that requests in synchronous while aiohttp does more advanced metrics.

increasing aiohttp timeout to 5 seconds

---

app/adzerk/api.py

Updating our timeout to 5 seconds decreased our number of 5xx errors. This proves that aiohttp timeouts operate differently than requests. To compensate we are increasing to 30 seconds.

updating timeout to 30 seconds

---

app/adzerk/api.py

Based on reading from https://docs.aiohttp.org/en/latest/http_request_lifecycle.html it looks like the aiohttp session was being re-used behind the scenes. The default behavior here is that when the session hits 100 connections all other connections will be put in a queue system and wait their turn. This correlated to exactly 100 breadcrumbs making a request in a sentry error.

Remove the limit on aiohttp connections

---

app/adzerk/api.py
app/main.py
images/app/Dockerfile

We are getting a lot of:
```
0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://e-site-id.adzerk.net/api/v2')
```
Looks like this is because clients are requesting sites with no ads to be served. Instead, we should log the error and return no ads to the clients.

Fix Sentry Integration & Decisions API Response

---

app/conf/adzerk.py
tests/unit/test_adzerk_api.py

Decrease the number of ads requested by default from 20 to 10, to accomplish two goals:
1. Improve stability, by avoiding big jumps in the request size, which require a scale-out. (See figure below.)
2. This was a request from ad-ops, because it might help with pacing: https://pocket.slack.com/archives/C01DGLNSFK9/p1612462133011500
Alternative solutions:
- Scale out faster when CPU is very high. Currently it takes 5 scale-out events over the course of 20 minutes to sufficiently decrease CPU usage.
- Solve the underlying performance problem, that makes the server sensitive to request size. This thread in FastAPI might be related: https://github.com/tiangolo/fastapi/issues/360#issuecomment-537839990

Decrease placement count from 20 to 10

---

app/conf/spocs.py

Give us control over whether collections are enabled, in order to decrease the number of ad decisions we need to make.
Collections in this context are a set of 3 or more stories that are run together on the Firefox New Tab. We only rarely run collections, but currently we're always requesting ad decisions for them.
- Specifying feature flags in code is low effort and guarantees good performance, but the approach will break down when this feature flag will have to be changed frequently. Currently that's not anticipated.
Slack thread:
- https://pocket.slack.com/archives/C4LD0T132/p1626449573016400

Add collections feature flag

---

app/adzerk/transform.py
tests/fixtures/mock_decision.py
tests/fixtures/mock_spoc.py

Update adzerk spoc template transformation. 
- Set default `min_score` = `0.1`
- Set default `item_score` = `0.2`
Opted to leave optional properties `domain_affinities` and `cta` untouched.
Slack: https://pocket.slack.com/archives/CR6T8BNCT/p1635287235002800
Ticket: https://getpocket.atlassian.net/browse/INFRA-148

fix: update spoc template transformation

---

images/nginx/Dockerfile

Support ended for this version of nginx, bumping to include security updates.
https://mozilla-hub.atlassian.net/browse/POC-63
https://endoflife.date/nginx

chore(nginx): Upgrade to an nginx getting security updates

---

images/nginx/nginx.conf

This was broken in 7c641327, since this isn't automatically deployed I am assuming we never noticed. If you try to start a new nginx image with that configuration it will error with:
```bash
2022/03/28 18:52:07 [emerg] 1#1: host not found in upstream "app:8000" in /etc/nginx/nginx.conf:29
nginx: [emerg] host not found in upstream "app:8000" in /etc/nginx/nginx.conf:29          
```

chore(nginx): POC-87 update server configuration

---

README.md

Fix the typos in the README (small chore PR, not ticketed).

chore(readme): Fix typos and numbering in an ordered list

---

Pipfile
README.md
app/main.py
cloudformation/README.md
cloudformation/proxy-service.yaml
docker-compose.yml
tests/unit/test_app.py

Remove Sentry from Proxy Server as detailed in the ticket.
Note - the Pipfile dependency for `sentry-sdk` remains included, as it was too risky to take it out given the repository has not been updated/deployed in a while.
https://getpocket.atlassian.net/browse/BACK-1573

chore(sentry): [BACK-1573] Remove Sentry from Proxy Server

---

Pipfile
Pipfile.lock

Currently, #74 is blocked by the CircleCI container environment wanting to install a copy of `brotlipy-0.7.0` Python package where its SHA from upstream doesn't match any of the SHAs in the Pipfile.lock.
One way to approach repairing this is explicitly installing the currently used version of brotlipy, which then adds & updates some brotlipy dependencies. This is the command used:
```
pipenv install --selective-upgrade --keep-outdated brotlipy==0.7.0
```
If we really want to restrict updates, we can pin the dependencies that are updated here (`importlib-metadata`, `zipp`). I'm considering new dependencies added as okay, but open to discussion on that. I've confirmed the hashes added for `brotlipy` include all the previously-used hashes as well (you can verify by checking out the …

Handle Brotlipy outdated hashes, option 2 (of many) - pipenv selective-upgrade

---

README.md
app/conf/geolocation.py

- We are moving from GeoIP2-City to GeoLite2-City database. Updated the name of the file the code is expecting to find in the S3 bucket (bucket has had new file uploaded already), updated README for local installation instructions.
https://getpocket.atlassian.net/browse/BACK-1696

fix(geolocation): [BACK-1696] Update GeoIP2 database

---

app/adzerk/api.py
app/client.py
app/main.py
app/provider/session_provider.py
tests/unit/test_app.py

To decrease latency by reusing HTTPS connections to Kevel.
Currently we create a ClientSession for each request, which prevents connection reuse. This moves aiohttp ClientSession to app startup and passes the session down to the Kevel client so that we can reuse the connections. In local testing this reduces latency by ~200ms.
It also adds a dummy cookie jar so that we're not reusing cookies across requests.
It retains the TCPConnector with the unlimited connection pool size, but this could be reduced now that connections will actually stay around.

Fix connection pooling

---

.github/workflows/openapi.yml
Pipfile
Pipfile.lock
openapi/openapi.yml
tests/api/test_api.py

Keep OpenAPI spec in the repository, and use generated tests to (a) verify the OpenAPI spec is correct and (b) have basic integration tests.
Used [schemathesis](https://github.com/schemathesis/schemathesis) for testing.
Left warnings in OpenAPI spec alone for the time being.

Add OpenAPI spec and spec-driven tests

---

openapi/openapi.yml

Without this, schemathesis generates values too large to fit into int32, which breaks MARS.
Unfortunately, `format: int32` is not enough to achieve the desired result, as it's only considered a hint and not a hard constraint.

Limit ad_types and zone_ids to positive int32 values

---

openapi/openapi.yml

Version 2 has been the default for /spocs for a long time, but the OpenAPI spec was never updated to reflect that.

Add version: 2 to OpenAPI spec

---

tests/api/test_api.py

This allows Schemathesis to actually test the response body. These tests were not failing because none of the response attributes are actually required.

Return decisions in API tests

---

openapi/openapi.yml
tests/api/test_api.py

- adding test cases for version=1 spocs requests
- separating collections test, since v2 will do different things based on the kevel response, whereas v1 will return the same shape for both kinds of kevel responses
This adds test cases for the spocs endpoint with collections returned from kevel. If the request version is 2 and the kevel response is a collection, then the shape of the response is adjusted slightly. [api spec definition](https://github.com/Pocket/proxy-server/pull/91/files#diff-f26912d4d2c7811bd456bf4f854b781a6a26384ea258dc55dfb592953cc4f9faR223-R227)
I removed the "default" value for version since that should be the server applied default if the value isn't supplied, but the field is required.
I also separated the tests by endpoint, so that it is more clear what kevel …

Add tests for collections

---

openapi/openapi.yml

Ensure that the openAPI spec matches the behavior of the service. In another review one of the fields was commented on which turned out to be missing from this spec. This led to me doing an audit reading the whole spec and the spocs/ handler code to get the two in sync.
I also updated the spec to be more strict about extra fields and which fields are required.
The SpocFeedItem object could have a bunch of fields marked required to match the assumptions the code is making about what is returned from Kevel, but I left that one as is for now. That portion I consolidated the two separate objects in the spec that both had to match the returned object and then removed the extra fields that those two objects had listed but would never be returned.
`pytest -s tests/api`
manually adjusted the code …

Audit openAPI spec for consistency with service

---

images/nginx/nginx.conf

On Jan 15th at 1amPT I received a page for the Proxy Server on it's CPU utilization. The service was trying to scale out in AWS and could not because it's tasks were dying with an essential container existing. Upon looking at the logs it seems that NGNIX was failing with an upstream not found.
I click-ops the service to retag an old NGINX image as latest for a temporary workaround.

fix(nginx): docker image upstream dns

---

app/telemetry/handler.py
tests/unit/test_telemetry_handler.py

Update the GCF to add processing for [Glean spoc ping](https://dictionary.telemetry.mozilla.org/apps/firefox_desktop/pings/spoc).  This ping is needed due to the removal of activity stream and the legacy `impression-stats` ping starting in Firefox version 122.
Replaces PR https://github.com/Pocket/proxy-server/pull/97
The previous version of the GCF relied on the structure of the JSON data to distinguish between desktop legacy `impression-stats` ping and Andoid Glean `spoc` ping.  This updated version relies on the attributes metadata included with the event.  Testing has been complete using production data to confirm the attribute dictionary does not require any decoding.

Added support for firefox-desktop Glean spoc ping

---

app/provider/sentry_provider.py

ClientDisconnect errors are getting sent to sentry in gcp (AWS deploy was not hooked up to sentry), and these errors can get raised when trying to parse a request json body.
The stacktrace is easy to see in the related sentry issue
https://mozilla.sentry.io/issues/4935558485/?project=4506543461302272
This mimics what bedrock is already doing for errors they have seen. https://github.com/bkochendorfer/bedrock/blob/b98c15e3e17a4d2d3e05afb75d6402d2f558a658/bedrock/settings/base.py#L1151
I haven't done any testing, not really sure what the best way would be to do so.
I think ideally these errors would be handled nicely by the application handler rather than raised as exceptions. I wasn't sure what other implications would be by adjusting this catch block …

filter client disconnect errors from sentry reporting

---

app/main.py
tests/unit/test_app.py

Now that we have visibility into errors in sentry, these have already started showing up. the 'version' param is assumed to be an integer but there is not any validation.
https://mozilla.sentry.io/issues/4935716151/?project=4506543461302272
try parsing the version param as an int before instantiating the client so that we can raise a parameter exception for a bad parameter.
`pipenv run pytest tests/unit/`

raise invalidParam exception to return a 400 when an invalid version is passed in

---

openapi/openapi.yml
tests/unit/test_app.py

the proxy supports query parameters for the spocs endpoint but they are not specified in the api spec. https://swagger.io/docs/specification/describing-parameters/ helped me figure out how to put these in the spec
https://github.com/Pocket/proxy-server/blob/main/app/main.py#L160-L162
* site, country, and region are the supported params
site is added as a param here, configured via `browser.newtabpage.activity-stream.discoverystream.spocSiteId`
https://searchfox.org/mozilla-central/source/browser/components/newtab/lib/DiscoveryStreamFeed.sys.mjs#627-631
country and region are configured via `browser.newtabpage.activity-stream.discoverystream.spocs-endpoint-query` which allows any query param to be appended to the spocs request
https://searchfox.org/mozilla-central/source/browser/components/ …

add supported query params for spocs endpoint

---

app/main.py
tests/unit/test_app.py

Handle more cases of bad input.
* unicode decode errors for bad json body https://mozilla.sentry.io/issues/4937115586/?project=4506543461302272 (I didn't add a test for this one, I couldn't figure out what bytes are causing it. So there is a new except handler for this error with no corresponding test
* invalid json body that passes parsing, but isn't a dict https://mozilla.sentry.io/issues/4937372907/?project=4506543461302272
* invalid placements https://mozilla.sentry.io/issues/4937867511/?project=4506543461302272
I tried going down the path of having fastAPI validate and parse request bodies, but ran into difficulties with the tests since we parse the ip address from the request as well.
https://fastapi.tiangolo.com/tutorial/body/
Since that was turning into a rabbit hole, I switched …

more parameter validations

---

app/client.py
app/main.py

1. I believe that ClientDisconnect exceptions getting raised from reading the post body and the client disconnecting are showing up as 500s on our graphs. We should handle disconnects gracefully since the client is no longer waiting for a response. [starlette requests.py](https://github.com/encode/starlette/blob/master/starlette/requests.py#L221-L253)
3. Looking at our logs in google is difficult because of the volume of noise. 40%+ of the logs are coming from ips not existing in our geo db.
[cloud logs](https://console.cloud.google.com/logs/query;query=resource.labels.container_name%3D%22pocket-proxy%22%0A--Hide%20similar%20entries%0A--%2528textPayload%3D~%22WARNING:root:Could%20not%20target%20based%20on%20geolocation%5C.%20The%20address%20%5B%5E%20%3D%5Ct%5Cn%5Cr%5Cf%5C%22%5C%2528%5C%252 …

handle ClientDisconnect errors raicsed when reading post body, don't log geo warnings on ip not in db

---

.circleci/config.yml
Pipfile
Pipfile.lock
app/telemetry/handler.py
app/telemetry/requirements.txt
tests/unit/test_telemetry_handler.py

We want to have visibility into the callback delays -- both contributed from the data pipeline and the overall delay from Kevel initially serving the impression to the impression callback occuring.
This data will be helpful to gauge the responsiveness to our system & gauge changes in behavior.
The overall delay can be queried in bigquery by doing a similar decoding of the shim, the stat emitted here in the log will be a little more accurate since querying the pings in bigquery does not have any data for when the cloud function was executed for the record.
Since there have been concerns on the cost of logs, this is implemented with an environment variable to control whether and how often we sample the events. This way we can easily turn it off or adjust the sample rate as needed.
`pipenv …

Add sampling support for latency metrics on ad server callbacks
